name: sharpy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster
  - apptools
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cmake
  - colorama
  - configobj
  - control
  - coverage
  - curl
  - cycler
  - dbus
  - dill
  - eigen
  - envisage
  - expat
  - freetype
  - future
  - gettext
  - glib
  - h5py
  - hdf4
  - hdf5
  - icu
  - jpeg
  - jsoncpp
  - kiwisolver
  - krb5
  - libcurl
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libnetcdf
  - libogg
  - libopenblas
  - libpng
  - libssh2
  - libtheora
  - libtiff
  - libvorbis
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mayavi
  - ncurses
  - numpy
  - numpy-base
  - openblas
  - openssl
  - pandas
  - pcre
  - pip
  - pyface
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - qt
  - readline
  - rhash
  - scipy
  - setuptools
  - sip
  - six
  - slycot
  - sqlite
  - tbb
  - tk
  - tornado
  - traits
  - traitsui
  - vtk
  - wheel
  - xlrd
  - xz
  - yaml
  - zlib
  - zstd
  - openpyxl

