name: Test Docker image build

on:
  pull_request:
    branches:
      - master
      - develop
      - 'rc*'
  push:
    paths:
      - 'utils/*'
      - 'Dockerfile'
      - '.github/workflows/docker*'

jobs:
  test_image_build:
    runs-on: ubuntu-latest
    name: Test Docker image build
    steps:
      - runs: 
        using: 'docker'
        image: 'Dockerfile'
