name: SHARPy Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - 'rc*'
    paths-ignore:
      - '*.py'
      - 'lib/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: macos_latest
    steps:
      - run: 'echo "No changes to python files, submodules or workflows, no run required" '
