name: Python package

on:
  pull_request:
    branches:
      - master
      - develop
      - 'rc*'
    paths-ignore:
      - '*.py'
      - 'lib/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No changes to python files, submodules or workflows, no run required'
